import { startTransition, useMemo, useCallback } from 'react';

/**
 * Hook to build clean, memoized or structured props for each module in AppRouter.
 * Keeps App.jsx slim, highly readable, and under 300 lines.
 */
export function useAppRouterProps({
  setCurrentTab,
  stockItems,
  machines,
  warehouseItemsComputed,
  mouvements,
  types,
  diagnostics,
  zones,
  technicians,
  operations,
  stockKPIs,
  filters,
  navigation,
  effectiveFamilies,
  effectiveTemplates,
  blueprints,
  compGroups,
  compFamilies,
  compTemplates,
  entrepotComponents,
  partTypes,
  partDesignations,
  rawStock,
  designations,
  families,
  templates,
  machineElementsLedger,
  addMachineElement,
  updateMachineElement,
  deleteMachineElement,
  duplicateBOMToTwins,
  preventiveTasks,
  preventiveActions,
  preventiveGuides,
  preventivePlans,
  preventiveExecutions,
  sortiesExterne,
  correctiveInterventions,
  activeLiveInterventionId,
  correctiveKpis,
  correctiveParetoAnomalies,
  correctiveParetoMachines,
  correctiveParetoTypes,
  correctivePreventiveRecommendations,
  correctiveActionsByPanne,
  correctivePanneCategories,
  correctiveTravauxAFaire,
  correctiveIntervenants,
  modals: {
    setShowAddArticleModal,
    setShowAddMachineModal,
    setShowAddUserModal,
    setAddUserModalType,
    setShowAddZoneModal,
  },
  handlers: {
    handleQuickSortie,
    handleAddMouvement,
    handleUpdateMouvement,
    handleDeleteMouvement,
    handleExportExcel,
    handleDownloadBlankTemplate,
    handleUpdateArticle,
    handleDirectAdjustStock,
    handleAddWarehouseItem,
    handleUpdateWarehouseItem,
    handleDeleteWarehouseItem,
    handleAddType,
    handleUpdateType,
    handleDeleteType,
    handleAddDesignation,
    handleUpdateDesignation,
    handleDeleteDesignation,
    handleAddMachine,
    handleUpdateMachine,
    handleDeleteMachine,
    handleAddCompGroup,
    handleUpdateCompGroup,
    handleDeleteCompGroup,
    handleAddCompFamily,
    handleUpdateCompFamily,
    handleDeleteCompFamily,
    handleAddCompTemplate,
    handleUpdateCompTemplate,
    handleDeleteCompTemplate,
    handleAddPartType,
    handleUpdatePartType,
    handleDeletePartType,
    handleAddPartDesignation,
    handleUpdatePartDesignation,
    handleDeletePartDesignation,
    handleAddFamily,
    handleUpdateFamily,
    handleDeleteFamily,
    handleAddTemplate,
    handleUpdateTemplate,
    handleDeleteTemplate,
    handleAddBlueprint,
    handleUpdateBlueprint,
    handleDeleteBlueprint,
    handleAddZone,
    handleUpdateZone,
    handleDeleteZone,
    handleAddTechnician,
    handleUpdateTechnician,
    handleDeleteTechnician,
    handleAddOperation,
    handleUpdateOperation,
    handleDeleteOperation,
    handleUpdateTask,
    handleDeleteTask,
    handleUpdateTaskCounter,
    handleMarkTaskDone,
    handleDeletePreventiveExecution,
    handleCreatePlanWithTasks,
    handleAddPreventiveAction,
    handleUpdatePreventiveAction,
    handleDeletePreventiveAction,
    handleAddPreventiveGuide,
    handleUpdatePreventiveGuide,
    handleDeletePreventiveGuide,
    handleResetPreventiveToBaseline,
    handleClearPreventiveForRealFactory,
    handleAddSortieExterne,
    handleUpdateSortieExterne,
    handleDeleteSortieExterne,
    handleMarkSortieReturned,
    handleMarkSortieMounted,
    handleClearSortiesForRealFactory,
    handleResetSortiesToBaseline,
    handleAddDemandeIntervention,
    handleConvertToBt,
    handleStartLiveIntervention,
    handleClotureIntervention,
    handleUpdateCorrectiveIntervention,
    handleDeleteCorrectiveIntervention,
    handleBulkImportCorrective,
    handleResetCorrectiveToSeed,
    handleGetCorrectiveActionsForPanne,
    handleAddCorrectiveActionForPanne,
    handleUpdateCorrectiveActionForPanne,
    handleDeleteCorrectiveActionForPanne,
    handleAddPanne,
    handleUpdatePanne,
    handleDeletePanne,
    handleAddTravail,
    handleUpdateTravail,
    handleDeleteTravail,
    handleResetCorrectiveActions,
    handleForceSyncCorrectiveSeed,
    handleLoadDemoData,
    handleClearAllForRealFactory,
    handleLoadDemoSection,
    handleClearDemoSection,
  },
  setters = {},
  showToast,
}) {
  const navigateTo = useCallback((tab) => startTransition(() => setCurrentTab(tab)), [setCurrentTab]);

  return useMemo(() => ({
    dashboard: {
      stockItems,
      machines,
      warehouseItems: warehouseItemsComputed,
      mouvements,
      types,
      diagnostics,
      zones,
      technicians,
      operations,
      stockKPIs,
      correctiveInterventions,
      correctiveKpis,
      onNavigateToStock: () => navigateTo('stock'),
      onNavigateToMachines: () => navigateTo('machines'),
      onNavigateToWarehouse: () => navigateTo('entrepot'),
      onNavigateToSortie: () => navigateTo('sortie'),
      onNavigateToPreventive: () => navigateTo('preventive'),
      onNavigateToCorrective: (targetTab = 'corrective') => navigateTo(typeof targetTab === 'string' ? targetTab : 'corrective'),
      onNavigateToZones: () => navigateTo('zones'),
      onNavigateToUsers: () => navigateTo('utilisateurs'),
      onNavigateToSettings: () => navigateTo('settings'),
      onQuickSortie: handleQuickSortie,
      onAddMouvement: handleAddMouvement,
      onUpdateMouvement: handleUpdateMouvement,
      onDeleteMouvement: handleDeleteMouvement,
      onExportExcel: handleExportExcel,
    },

    stock: {
      stockItems,
      mouvements,
      stockSearch: filters.stockSearch,
      setStockSearch: filters.setStockSearch,
      stockTypeFilter: filters.stockTypeFilter,
      setStockTypeFilter: filters.setStockTypeFilter,
      stockAlertOnly: filters.stockAlertOnly,
      setStockAlertOnly: filters.setStockAlertOnly,
      types,
      zones,
      machines,
      technicians,
      operations,
      onOpenAddArticle: () => setShowAddArticleModal(true),
      onQuickSortie: handleQuickSortie,
      onAddMouvement: handleAddMouvement,
      onUpdateArticle: handleUpdateArticle,
      onDirectAdjustStock: handleDirectAdjustStock,
      stockKPIs,
      onNavigateToType: navigation.handleNavigateToStockFiltered,
      onNavigateToTypes: () => navigateTo('types'),
      onNavigateToDesignations: navigation.handleNavigateToDesignationsFiltered,
      onNavigateToSortie: () => navigateTo('sortie'),
    },

    sortie: {
      mouvements,
      stockItems,
      warehouseItems: warehouseItemsComputed,
      machineElementsLedger,
      updateMachineElement,
      quickSortiePreset: filters.quickSortiePreset,
      setQuickSortiePreset: filters.setQuickSortiePreset,
      families,
      templates,
      types,
      diagnostics,
      zones,
      machines,
      technicians,
      operations,
      sortiesExterne,
      onAddSortieExterne: handleAddSortieExterne,
      onUpdateSortieExterne: handleUpdateSortieExterne,
      onDeleteSortieExterne: handleDeleteSortieExterne,
      onMarkSortieReturned: handleMarkSortieReturned,
      onMarkSortieMounted: handleMarkSortieMounted,
      onClearSortiesForRealFactory: handleClearSortiesForRealFactory,
      onResetSortiesToBaseline: handleResetSortiesToBaseline,
      onAddMouvement: handleAddMouvement,
      onUpdateMouvement: handleUpdateMouvement,
      onDeleteMouvement: handleDeleteMouvement,
      onDirectAdjustStock: handleDirectAdjustStock,
      onAddWarehouseItem: handleAddWarehouseItem,
      onUpdateWarehouseItem: handleUpdateWarehouseItem,
      onOpenAddArticle: () => setShowAddArticleModal(true),
      onOpenAddMachine: () => setShowAddMachineModal(true),
      onOpenAddZone: () => setShowAddZoneModal(true),
      onOpenAddTech: () => {
        setAddUserModalType('TECHNICIEN');
        setShowAddUserModal(true);
      },
      onOpenAddChef: () => {
        setAddUserModalType('RESPONSABLE');
        setShowAddUserModal(true);
      },
      onOpenAddOperator: () => {
        setAddUserModalType('OPERATEUR');
        setShowAddUserModal(true);
      },
      onNavigateToWarehouse: () => navigateTo('entrepot'),
      onNavigateToStockFilteredByRef: navigation.handleNavigateToStockFilteredByRef,
    },

    entrepot: {
      warehouseItems: warehouseItemsComputed,
      entrepotComponents,
      mouvements,
      compFamilies,
      compTemplates,
      partTypes,
      partDesignations,
      machines,
      whSearch: filters.whSearch,
      setWhSearch: filters.setWhSearch,
      whFamilyFilter: filters.whFamilyFilter,
      setWhFamilyFilter: filters.setWhFamilyFilter,
      whTemplateFilter: filters.whTemplateFilter,
      setWhTemplateFilter: filters.setWhTemplateFilter,
      whTypeFilter: filters.whTypeFilter,
      setWhTypeFilter: filters.setWhTypeFilter,
      whNatureFilter: filters.whNatureFilter,
      setWhNatureFilter: filters.setWhNatureFilter,
      onAddWarehouseItem: handleAddWarehouseItem,
      onUpdateWarehouseItem: handleUpdateWarehouseItem,
      onDeleteWarehouseItem: handleDeleteWarehouseItem,
      onNavigateToCompFamilies: navigation.handleNavigateToCompFamilies,
      onNavigateToCompTemplates: navigation.handleNavigateToCompTemplates,
      onNavigateToPartTypes: navigation.handleNavigateToPartTypes,
      onNavigateToPartDesignations: navigation.handleNavigateToPartDesignations,
      onNavigateToEntrepotByPart: navigation.handleNavigateToEntrepotByPart,
    },

    types: {
      types,
      designations: diagnostics || designations,
      stockItems,
      onAddType: handleAddType,
      onUpdateType: handleUpdateType,
      onDeleteType: handleDeleteType,
      onNavigateToStockFiltered: navigation.handleNavigateToStockFiltered,
      onNavigateToDesignationsFiltered: navigation.handleNavigateToDesignationsFiltered,
      onQuickCreateDesignation: navigation.handleNavigateToCreateDesignationForType,
    },

    designations: {
      designations: diagnostics || designations,
      types,
      stockItems,
      desigTypeFilter: filters.diagTypeFilter,
      setDesigTypeFilter: filters.setDiagTypeFilter,
      quickCreateType: filters.quickCreateDesignationType,
      setQuickCreateType: filters.setQuickCreateDesignationType,
      onReturnToTypes: () => navigateTo('types'),
      onAddDesignation: handleAddDesignation,
      onUpdateDesignation: handleUpdateDesignation,
      onDeleteDesignation: handleDeleteDesignation,
      onOpenAddTypeModal: () => navigateTo('types'),
      onNavigateToStockFilteredByRef: navigation.handleNavigateToStockFilteredByRef,
      onNavigateToStockFilteredByType: navigation.handleNavigateToStockFiltered,
      onNavigateToQuickSortie: navigation.handleNavigateToQuickSortieFromDesignation,
    },

    machines: {
      machines,
      families: effectiveFamilies,
      templates: effectiveTemplates,
      blueprints,
      zones,
      technicians,
      stockItems,
      warehouseItems: warehouseItemsComputed,
      mouvements,
      search: filters.mchSearch,
      setSearch: filters.setMchSearch,
      mchFamilyFilter: filters.mchFamilyFilter,
      setMchFamilyFilter: filters.setMchFamilyFilter,
      mchTemplateFilter: filters.mchTemplateFilter,
      setMchTemplateFilter: filters.setMchTemplateFilter,
      mchZoneFilter: filters.mchZoneFilter,
      setMchZoneFilter: filters.setMchZoneFilter,
      onAddMachine: handleAddMachine,
      onUpdateMachine: handleUpdateMachine,
      onDeleteMachine: handleDeleteMachine,
      onOpenAddMachine: () => setShowAddMachineModal(true),
      onNavigateToFamily: navigation.handleNavigateToFamilyFiltered,
      onNavigateToTemplate: navigation.handleNavigateToTemplatesFiltered,
      onNavigateToZone: navigation.handleNavigateToMachinesByZone,
      onNavigateToBlueprints: navigation.handleNavigateToBlueprintsFiltered,
      onNavigateToQuickSortie: navigation.handleNavigateToQuickSortieFromMachine,
      onNavigateToPreventive: (_machId) => navigateTo('preventive'),
    },

    compGroups: {
      compGroups,
      compFamilies,
      compTemplates,
      entrepotComponents,
      warehouseItems: warehouseItemsComputed,
      onAddCompGroup: handleAddCompGroup,
      onUpdateCompGroup: handleUpdateCompGroup,
      onDeleteCompGroup: handleDeleteCompGroup,
      onNavigateToCompFamilies: navigation.handleNavigateToCompFamiliesByGroup,
      onNavigateToCompTemplates: navigation.handleNavigateToCompTemplatesByGroup,
    },

    compFamilies: {
      compGroups,
      compFamilies,
      compTemplates,
      entrepotComponents,
      warehouseItems: warehouseItemsComputed,
      groupFilter: filters.compFamilyGroupFilter,
      setGroupFilter: filters.setCompFamilyGroupFilter,
      search: filters.whSearch,
      setSearch: filters.setWhSearch,
      onAddCompFamily: handleAddCompFamily,
      onUpdateCompFamily: handleUpdateCompFamily,
      onDeleteCompFamily: handleDeleteCompFamily,
      onNavigateToCompTemplates: navigation.handleNavigateToCompTemplates,
      onQuickCreateCompTemplate: navigation.handleNavigateToCreateCompTemplateForFamily,
      onNavigateToEntrepotByFamily: (familyId) => navigation.handleNavigateToEntrepotByComp(familyId, 'ALL'),
      onNavigateToCompGroups: navigation.handleNavigateToCompGroups,
    },

    compTemplates: {
      compGroups,
      compTemplates,
      compFamilies,
      entrepotComponents,
      warehouseItems: warehouseItemsComputed,
      search: filters.whSearch,
      setSearch: filters.setWhSearch,
      groupFilter: filters.compTemplateGroupFilter,
      setGroupFilter: filters.setCompTemplateGroupFilter,
      compTemplateGroupFilter: filters.compTemplateGroupFilter,
      setCompTemplateGroupFilter: filters.setCompTemplateGroupFilter,
      familyFilter: filters.compTemplateFamilyFilter,
      setFamilyFilter: filters.setCompTemplateFamilyFilter,
      compTemplateFamilyFilter: filters.compTemplateFamilyFilter,
      setCompTemplateFamilyFilter: filters.setCompTemplateFamilyFilter,
      quickCreateFamily: filters.quickCreateCompTemplateFamily,
      setQuickCreateFamily: filters.setQuickCreateCompTemplateFamily,
      onReturnToFamilies: () => navigateTo('comp_families'),
      onAddCompTemplate: handleAddCompTemplate,
      onUpdateCompTemplate: handleUpdateCompTemplate,
      onDeleteCompTemplate: handleDeleteCompTemplate,
      onOpenAddFamilyModal: () => navigateTo('comp_families'),
      onNavigateToEntrepotByTemplate: navigation.handleNavigateToEntrepotByComp,
      onNavigateToCompFamilies: (familyId) => {
        if (familyId) navigation.handleNavigateToCompTemplates(familyId);
        else navigateTo('comp_families');
      },
      onNavigateToQuickSortie: navigation.handleNavigateToQuickSortieFromCompTemplate,
      onNavigateToCompGroups: navigation.handleNavigateToCompGroups,
    },

    partTypes: {
      partTypes,
      partDesignations,
      warehouseItems: warehouseItemsComputed,
      search: filters.whSearch,
      setSearch: filters.setWhSearch,
      onAddPartType: handleAddPartType,
      onUpdatePartType: handleUpdatePartType,
      onDeletePartType: handleDeletePartType,
      onNavigateToPartDesignations: navigation.handleNavigateToPartDesignations,
      onNavigateToEntrepotByType: navigation.handleNavigateToEntrepotByType,
    },

    partDesignations: {
      partDesignations,
      partTypes,
      warehouseItems: warehouseItemsComputed,
      search: filters.whSearch,
      setSearch: filters.setWhSearch,
      partDesignationTypeFilter: filters.partDesignationTypeFilter,
      setPartDesignationTypeFilter: filters.setPartDesignationTypeFilter,
      onAddPartDesignation: handleAddPartDesignation,
      onUpdatePartDesignation: handleUpdatePartDesignation,
      onDeletePartDesignation: handleDeletePartDesignation,
      onNavigateToPartTypes: navigation.handleNavigateToPartTypes,
      onNavigateToEntrepotByPart: navigation.handleNavigateToEntrepotByPart,
      onNavigateToEntrepotByType: navigation.handleNavigateToEntrepotByType,
      onNavigateToQuickSortie: navigation.handleNavigateToQuickSortieFromPartDesignation,
    },

    families: {
      families: effectiveFamilies,
      templates: effectiveTemplates,
      machines,
      search: filters.whSearch,
      setSearch: filters.setWhSearch,
      onAddFamily: handleAddFamily,
      onUpdateFamily: handleUpdateFamily,
      onDeleteFamily: handleDeleteFamily,
      onNavigateToTemplatesFiltered: navigation.handleNavigateToTemplatesFiltered,
      onQuickCreateTemplate: navigation.handleNavigateToCreateTemplateForFamily,
      onNavigateToMachinesByFamily: navigation.handleNavigateToMachinesByFamily,
    },

    templates: {
      templates: effectiveTemplates,
      families: effectiveFamilies,
      machines,
      search: filters.whSearch,
      setSearch: filters.setWhSearch,
      templateFamilyFilter: filters.templateFamilyFilter,
      setTemplateFamilyFilter: filters.setTemplateFamilyFilter,
      quickCreateTemplateFamily: filters.quickCreateTemplateFamily,
      setQuickCreateTemplateFamily: filters.setQuickCreateTemplateFamily,
      onAddTemplate: handleAddTemplate,
      onUpdateTemplate: handleUpdateTemplate,
      onDeleteTemplate: handleDeleteTemplate,
      onOpenAddFamilyModal: () => navigateTo('families'),
      onNavigateToMachinesByTemplate: navigation.handleNavigateToMachinesByTemplate,
      onNavigateToFamilyFiltered: navigation.handleNavigateToFamilyFiltered,
      onNavigateToBlueprints: navigation.handleNavigateToBlueprintsFiltered,
      onQuickCreateBlueprint: navigation.handleNavigateToCreateBlueprintForTemplate,
    },

    blueprints: {
      blueprints,
      templates: effectiveTemplates,
      families: effectiveFamilies,
      machines,
      compFamilies,
      compTemplates,
      partTypes,
      partDesignations,
      stockItems,
      warehouseItems: warehouseItemsComputed,
      mouvements,
      quickCreateBlueprintPreset: filters.quickCreateBlueprintPreset,
      setQuickCreateBlueprintPreset: filters.setQuickCreateBlueprintPreset,
      blueprintFamilyFilter: filters.blueprintFamilyFilter,
      setBlueprintFamilyFilter: filters.setBlueprintFamilyFilter,
      blueprintTemplateFilter: filters.blueprintTemplateFilter,
      setBlueprintTemplateFilter: filters.setBlueprintTemplateFilter,
      onAddBlueprint: handleAddBlueprint,
      onUpdateBlueprint: handleUpdateBlueprint,
      onDeleteBlueprint: handleDeleteBlueprint,
      onOpenAddFamilyModal: () => navigateTo('families'),
      onOpenAddTemplateModal: () => navigateTo('templates'),
      onNavigateToMachinesByTemplate: navigation.handleNavigateToMachinesByTemplate,
      onNavigateToFamily: navigation.handleNavigateToFamilyFiltered,
      onNavigateToTemplate: navigation.handleNavigateToTemplatesFiltered,
      onNavigateToTab: navigateTo,
    },

    zones: {
      zones,
      machines,
      technicians,
      operations,
      search: filters.whSearch,
      setSearch: filters.setWhSearch,
      onAddZone: handleAddZone,
      onUpdateZone: handleUpdateZone,
      onDeleteZone: handleDeleteZone,
      onNavigateToTechs: navigation.handleNavigateToTechsByZone,
      onNavigateToOps: navigation.handleNavigateToOpsByZone,
      onNavigateToMachines: navigation.handleNavigateToMachinesByZone,
      onOpenAddZoneModal: () => setShowAddZoneModal(true),
    },

    utilisateurs: {
      technicians,
      operations,
      zones,
      mouvements,
      techZoneFilter: filters.techZoneFilter,
      setTechZoneFilter: filters.setTechZoneFilter,
      opZoneFilter: filters.opZoneFilter,
      setOpZoneFilter: filters.setOpZoneFilter,
      onAddTechnician: handleAddTechnician,
      onUpdateTechnician: handleUpdateTechnician,
      onDeleteTechnician: handleDeleteTechnician,
      onAddOperation: handleAddOperation,
      onUpdateOperation: handleUpdateOperation,
      onDeleteOperation: handleDeleteOperation,
      onOpenAddArticle: () => setShowAddArticleModal(true),
      onOpenAddMachine: () => setShowAddMachineModal(true),
      onOpenAddZone: () => setShowAddZoneModal(true),
      onOpenAddTechModal: () => {
        setAddUserModalType('TECHNICIEN');
        setShowAddUserModal(true);
      },
      onOpenAddRespModal: () => {
        setAddUserModalType('RESPONSABLE');
        setShowAddUserModal(true);
      },
      onOpenAddOpModal: () => {
        setAddUserModalType('OPERATEUR');
        setShowAddUserModal(true);
      },
    },

    settings: {
      rawStock,
      setRawStock: setters.setRawStock,
      stockItems,
      machines,
      setMachines: setters.setMachines,
      mouvements,
      setMouvements: setters.setMouvements,
      types,
      setTypes: setters.setTypes,
      designations,
      setDesignations: setters.setDesignations,
      zones,
      setZones: setters.setZones,
      technicians,
      setTechnicians: setters.setTechnicians,
      operations,
      setOperations: setters.setOperations,
      compFamilies,
      compTemplates,
      partTypes,
      partDesignations,
      families: effectiveFamilies,
      setFamilies: setters.setFamilies,
      templates: effectiveTemplates,
      setTemplates: setters.setTemplates,
      warehouseItems: warehouseItemsComputed,
      sortiesExterne,
      preventiveTasks,
      setPreventiveTasks: setters.setPreventiveTasks,
      correctiveInterventions,
      setCorrectiveInterventions: setters.setCorrectiveInterventions,
      onResetCorrective: handleResetCorrectiveToSeed,
      onBulkImportCorrective: handleBulkImportCorrective,
      onLoadDemoData: handleLoadDemoData,
      onClearAllForRealFactory: handleClearAllForRealFactory,
      onLoadDemoSection: handleLoadDemoSection,
      onClearDemoSection: handleClearDemoSection,
      onExportExcel: handleExportExcel,
      onDownloadBlankTemplate: handleDownloadBlankTemplate,
      onNavigateToWarehouse: () => navigateTo('entrepot'),
      showToast,
    },

    nexus: {
      types,
      diagnostics,
      families: effectiveFamilies,
      templates: effectiveTemplates,
      blueprints,
      zones,
      technicians,
      operations,
      machines,
      stockItems,
      compFamilies,
      compTemplates,
      partTypes,
      partDesignations,
      warehouseItems: warehouseItemsComputed,
      mouvements,
      machineElementsLedger,
      onAddMachineElement: addMachineElement,
      onUpdateMachineElement: updateMachineElement,
      onDeleteMachineElement: deleteMachineElement,
      onDuplicateBOMToTwins: duplicateBOMToTwins,
      onNavigate: navigateTo,
      showToast,
    },

    preventive: {
      tasks: preventiveTasks,
      actions: preventiveActions,
      guides: preventiveGuides,
      plans: preventivePlans,
      executions: preventiveExecutions,
      onUpdateTask: handleUpdateTask,
      onDeleteTask: handleDeleteTask,
      onUpdateTaskCounter: handleUpdateTaskCounter,
      onMarkTaskDone: handleMarkTaskDone,
      onDeleteExecution: handleDeletePreventiveExecution,
      onResetToBaseline: (ctx) => handleResetPreventiveToBaseline({ machines, ...ctx }),
      onClearPreventiveForRealFactory: (ctx) => handleClearPreventiveForRealFactory({ machines, ...ctx }),
      machines,
      zones,
      technicians,
      stockItems,
      warehouseItems: warehouseItemsComputed,
      mouvements,
      onAddMouvement: handleAddMouvement,
      onDirectAdjustStock: handleDirectAdjustStock,
      onUpdateMachine: handleUpdateMachine,
      showToast: navigation?.showToast,
      onNavigateToMachine: (_machId) => navigateTo('machines'),
      onNavigateToReferentiel: () => navigateTo('preventive_referentiel'),
      onCreateCorrective: (payload) => {
        if (navigation?.showToast) {
          navigation.showToast(`BT Correctif ${payload.id_bt} créé avec succès !`, 'info');
        }
      },
    },

    preventiveReferentiel: {
      tasks: preventiveTasks,
      actions: preventiveActions,
      guides: preventiveGuides,
      plans: preventivePlans,
      onAddAction: handleAddPreventiveAction,
      onUpdateAction: handleUpdatePreventiveAction,
      onDeleteAction: handleDeletePreventiveAction,
      onAddGuide: handleAddPreventiveGuide,
      onUpdateGuide: handleUpdatePreventiveGuide,
      onDeleteGuide: handleDeletePreventiveGuide,
      onCreatePlanWithTasks: handleCreatePlanWithTasks,
      onResetToBaseline: (ctx) => handleResetPreventiveToBaseline({ machines, ...ctx }),
      onClearPreventiveForRealFactory: (ctx) => handleClearPreventiveForRealFactory({ machines, ...ctx }),
      machines,
      zones,
      technicians,
      stockItems,
      warehouseItems: warehouseItemsComputed,
      blueprints,
      compTemplates,
      compFamilies,
      mouvements,
      onAddMouvement: handleAddMouvement,
      onDirectAdjustStock: handleDirectAdjustStock,
      showToast: navigation?.showToast,
      onNavigateToMainView: () => navigateTo('preventive'),
      preventiveRecommendations: correctivePreventiveRecommendations,
    },

    corrective: {
      interventions: correctiveInterventions,
      activeLiveId: activeLiveInterventionId,
      setActiveLiveId: handleStartLiveIntervention,
      kpis: correctiveKpis,
      paretoAnomalies: correctiveParetoAnomalies,
      paretoMachines: correctiveParetoMachines,
      paretoTypes: correctiveParetoTypes,
      preventiveRecommendations: correctivePreventiveRecommendations,
      actionsByPanne: correctiveActionsByPanne,
      panneCategories: correctivePanneCategories,
      travauxAFaire: correctiveTravauxAFaire,
      intervenants: correctiveIntervenants,
      getActionsForPanne: handleGetCorrectiveActionsForPanne,
      onAddActionForPanne: handleAddCorrectiveActionForPanne,
      onUpdateActionForPanne: handleUpdateCorrectiveActionForPanne,
      onDeleteActionForPanne: handleDeleteCorrectiveActionForPanne,
      onAddPanne: handleAddPanne,
      onUpdatePanne: handleUpdatePanne,
      onDeletePanne: handleDeletePanne,
      onAddTravail: handleAddTravail,
      onUpdateTravail: handleUpdateTravail,
      onDeleteTravail: handleDeleteTravail,
      onResetActionsToSeed: handleResetCorrectiveActions,
      onForceSyncSeed: handleForceSyncCorrectiveSeed,
      onAddDemande: handleAddDemandeIntervention,
      onConvertToBt: handleConvertToBt,
      onStartLive: handleStartLiveIntervention,
      onClotureIntervention: (id, clotureData, customMvtHandler) =>
        handleClotureIntervention(id, clotureData, customMvtHandler || handleAddMouvement),
      onUpdateIntervention: handleUpdateCorrectiveIntervention,
      onDeleteIntervention: handleDeleteCorrectiveIntervention,
      onBulkImport: handleBulkImportCorrective,
      onResetToSeed: (ctx) => handleResetCorrectiveToSeed({ machines, ...ctx }),
      machines,
      zones,
      technicians,
      onAddTechnician: handleAddTechnician,
      onUpdateTechnician: handleUpdateTechnician,
      onDeleteTechnician: handleDeleteTechnician,
      stockItems,
      warehouseItems: warehouseItemsComputed,
      onAddMouvement: handleAddMouvement,
      onAddPreventiveTask: handleAddPreventiveAction,
      showToast: navigation?.showToast,
      onNavigateToTab: navigateTo,
    },

    guide: {},
  }), [
    stockItems,
    machines,
    warehouseItemsComputed,
    mouvements,
    types,
    diagnostics,
    zones,
    technicians,
    operations,
    stockKPIs,
    filters,
    navigation,
    effectiveFamilies,
    effectiveTemplates,
    blueprints,
    compGroups,
    compFamilies,
    compTemplates,
    partTypes,
    partDesignations,
    rawStock,
    designations,
    families,
    templates,
    navigateTo,
    handleQuickSortie,
    handleAddMouvement,
    handleUpdateMouvement,
    handleDeleteMouvement,
    handleExportExcel,
    handleUpdateArticle,
    handleDirectAdjustStock,
    handleAddWarehouseItem,
    handleUpdateWarehouseItem,
    handleDeleteWarehouseItem,
    handleAddType,
    handleUpdateType,
    handleDeleteType,
    handleAddDesignation,
    handleUpdateDesignation,
    handleDeleteDesignation,
    handleAddMachine,
    handleUpdateMachine,
    handleDeleteMachine,
    handleAddCompGroup,
    handleUpdateCompGroup,
    handleDeleteCompGroup,
    handleAddCompFamily,
    handleUpdateCompFamily,
    handleDeleteCompFamily,
    handleAddCompTemplate,
    handleUpdateCompTemplate,
    handleDeleteCompTemplate,
    handleAddPartType,
    handleUpdatePartType,
    handleDeletePartType,
    handleAddPartDesignation,
    handleUpdatePartDesignation,
    handleDeletePartDesignation,
    handleAddZone,
    handleUpdateZone,
    handleDeleteZone,
    handleAddTechnician,
    handleUpdateTechnician,
    handleDeleteTechnician,
    handleAddOperation,
    handleUpdateOperation,
    handleDeleteOperation,
    preventiveTasks,
    preventiveActions,
    preventiveGuides,
    preventivePlans,
    preventiveExecutions,
    handleUpdateTask,
    handleMarkTaskDone,
    handleDeletePreventiveExecution,
    handleCreatePlanWithTasks,
    handleAddPreventiveAction,
    handleUpdatePreventiveAction,
    handleDeletePreventiveAction,
    handleAddPreventiveGuide,
    handleUpdatePreventiveGuide,
    handleDeletePreventiveGuide,
    handleResetPreventiveToBaseline,
    handleClearPreventiveForRealFactory,
    sortiesExterne,
    handleAddSortieExterne,
    handleUpdateSortieExterne,
    handleDeleteSortieExterne,
    handleMarkSortieReturned,
    handleMarkSortieMounted,
    handleClearSortiesForRealFactory,
    handleResetSortiesToBaseline,
    correctiveInterventions,
    activeLiveInterventionId,
    correctiveKpis,
    correctiveParetoAnomalies,
    correctiveParetoMachines,
    correctiveParetoTypes,
    correctivePreventiveRecommendations,
    correctiveActionsByPanne,
    correctivePanneCategories,
    correctiveTravauxAFaire,
    correctiveIntervenants,
    handleAddDemandeIntervention,
    handleConvertToBt,
    handleStartLiveIntervention,
    handleClotureIntervention,
    handleUpdateCorrectiveIntervention,
    handleDeleteCorrectiveIntervention,
    handleBulkImportCorrective,
    handleResetCorrectiveToSeed,
    setShowAddArticleModal,
    setShowAddMachineModal,
    setShowAddUserModal,
    setAddUserModalType,
    setShowAddZoneModal,
  ]);
}
