import {  useState, useMemo, useRef, useEffect  } from 'react';
import { LayoutGrid, Check, X, RotateCcw, Sparkles } from 'lucide-react';

/**
 * Standard 5 bands of numbers from 01 to 99
 */
const DEFAULT_BANDS_99 = [
  { id: '1-20', label: '01 - 20', start: 1, end: 20 },
  { id: '21-40', label: '21 - 40', start: 21, end: 40 },
  { id: '41-60', label: '41 - 60', start: 41, end: 60 },
  { id: '61-80', label: '61 - 80', start: 61, end: 80 },
  { id: '81-99', label: '81 - 99', start: 81, end: 99 },
];

/**
 * SequentialCodePicker Component
 *
 * Architecture & Philosophy:
 * - 100% Offline, Pure SVG icons (lucide-react LayoutGrid).
 * - Light Excel UI aesthetic: Crisp borders, zero clunky nested boxes, high contrast.
 * - Non-destructive: Generates next sequential ID by default while offering full flexibility to assign custom free slots.
 * - Integrity protection: Automatically detects taken numbers (Set) and renders them muted, crossed out, and unclickable.
 * - Responsive: Adaptive grid (5 columns by default, 10 on wide screens) and fluid popover attached under the target input.
 *
 * @param {string} prefix - Entity prefix (e.g., 'TECH-', 'OP-', 'RESP-', 'MCH-', 'ZONE-', 'FAM-', 'TYP-', 'BON-')
 * @param {string} currentCode - Current active or selected code (e.g., 'TECH-04')
 * @param {function} onChangeCode - Callback invoked when a number is selected or reset
 * @param {string} autoGeneratedCode - Default sequential code calculated by system
 * @param {Set<number>} takenNumbers - Set of numbers already assigned in the database/localStorage
 * @param {boolean} disabled - Disable interaction if in edit mode or read-only
 * @param {string} label - Input label displayed above the field
 * @param {string} helperText - Subtitle or description below the field
 * @param {number} maxNumbers - Maximum selectable number (default: 99)
 * @param {number} padLength - Number of digits formatting (default: 2 -> '01', '02'...)
 * @param {Array} customBands - Optional customized bands array
 */
export default function SequentialCodePicker({
  prefix = 'CODE-',
  currentCode = '',
  onChangeCode = () => {},
  autoGeneratedCode = '',
  takenNumbers = new Set(),
  disabled = false,
  label = 'Code Identifiant',
  helperText = 'Code séquentiel généré automatiquement avec choix libre du numéro',
  maxNumbers = 99,
  padLength = 2,
  customBands = null,
}) {
  const [isOpen, setIsOpen] = useState(false);
  const bands = customBands || DEFAULT_BANDS_99;
  const [activeBandId, setActiveBandId] = useState(bands[0]?.id || '1-20');
  const containerRef = useRef(null);

  // Extract currently selected numeric value from currentCode
  const selectedNumber = useMemo(() => {
    if (!currentCode) return null;
    const match =
      String(currentCode).match(new RegExp(`${prefix}(\\d+)`, 'i')) ||
      String(currentCode).match(/-(\d+)$/);
    return match ? parseInt(match[1], 10) : null;
  }, [currentCode, prefix]);

  // If selected number is outside current active band, auto-switch to that band on open
  useEffect(() => {
    if (isOpen && selectedNumber) {
      const matchingBand = bands.find(
        (b) => selectedNumber >= b.start && selectedNumber <= b.end
      );
      if (matchingBand) {
        setActiveBandId(matchingBand.id);
      }
    }
  }, [isOpen, selectedNumber, bands]);

  // Click outside to dismiss popover
  useEffect(() => {
    function handleClickOutside(event) {
      if (containerRef.current && !containerRef.current.contains(event.target)) {
        setIsOpen(false);
      }
    }
    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside);
    }
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [isOpen]);

  // Available and taken count calculation
  const totalTaken = useMemo(() => {
    let count = 0;
    for (let i = 1; i <= maxNumbers; i++) {
      if (takenNumbers.has(i)) count++;
    }
    return count;
  }, [takenNumbers, maxNumbers]);

  const totalAvailable = Math.max(0, maxNumbers - totalTaken);

  // Active numbers to display based on selected band or 'all'
  const displayedNumbers = useMemo(() => {
    if (activeBandId === 'all') {
      const nums = [];
      for (let i = 1; i <= maxNumbers; i++) nums.push(i);
      return nums;
    }
    const band = bands.find((b) => b.id === activeBandId) || bands[0];
    if (!band) return [];
    const nums = [];
    for (let i = band.start; i <= Math.min(band.end, maxNumbers); i++) {
      nums.push(i);
    }
    return nums;
  }, [activeBandId, bands, maxNumbers]);

  // Select number handler
  const handleSelectNumber = (num) => {
    if (takenNumbers.has(num)) return;
    const padded = String(num).padStart(padLength, '0');
    const newCode = `${prefix}${padded}`;
    onChangeCode(newCode);
    setIsOpen(false);
  };

  // Revert to auto sequential code
  const handleResetToAuto = () => {
    if (autoGeneratedCode) {
      onChangeCode(autoGeneratedCode);
    }
  };

  const isCustomized = Boolean(
    autoGeneratedCode && currentCode && currentCode !== autoGeneratedCode
  );

  return (
    <div className="relative w-full" ref={containerRef}>
      {/* Label and Reset Link */}
      <div className="flex items-center justify-between mb-1.5">
        <label className="text-[11px] font-bold uppercase tracking-wider text-slate-700 flex items-center gap-1.5">
          <span>{label}</span>
          <span className="text-[10px] font-mono text-slate-400 font-normal">
            ({prefix}
            {String(1).padStart(padLength, '0')} - {prefix}
            {String(maxNumbers).padStart(padLength, '0')})
          </span>
        </label>

        {isCustomized && (
          <button
            type="button"
            onClick={handleResetToAuto}
            className="text-[10.5px] font-semibold text-indigo-600 hover:text-indigo-800 flex items-center gap-1 cursor-pointer transition"
            title="Revenir au code séquentiel automatique par défaut"
          >
            <RotateCcw className="w-3 h-3" />
            <span>Auto ({autoGeneratedCode})</span>
          </button>
        )}
      </div>

      {/* Main Input Display Field with Clean Offline SVG Icon */}
      <div
        className={`w-full h-10 px-3 rounded-xl bg-white border transition-all flex items-center justify-between shadow-2xs ${
          isOpen
            ? 'border-indigo-500 ring-2 ring-indigo-500/15'
            : 'border-slate-200 hover:border-slate-300'
        }`}
      >
        {/* Unified clean code input without inner frames or boxes around digits */}
        <div className="flex items-center gap-2 min-w-0 flex-1 mr-2">
          <input
            type="text"
            disabled={disabled}
            value={currentCode}
            onChange={(e) => onChangeCode(e.target.value.toUpperCase())}
            placeholder={`${prefix}${String(1).padStart(padLength, '0')}`}
            className="font-mono text-sm font-bold text-slate-900 tracking-wider bg-transparent outline-none w-full min-w-0 uppercase"
          />

          {isCustomized ? (
            <span className="text-[10px] font-semibold text-amber-700 bg-amber-50 px-2 py-0.5 rounded-md border border-amber-200/70 shrink-0">
              Personnalisé
            </span>
          ) : (
            <span className="text-[10px] font-semibold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-md border border-emerald-200/70 shrink-0">
              Séquentiel
            </span>
          )}
        </div>

        {/* Clean, pure offline SVG icon trigger */}
        <button
          type="button"
          disabled={disabled}
          onClick={() => setIsOpen((prev) => !prev)}
          className={`w-7 h-7 rounded-lg flex items-center justify-center transition cursor-pointer ${
            isOpen
              ? 'bg-indigo-600 text-white shadow-2xs'
              : 'text-slate-400 hover:text-indigo-600 hover:bg-indigo-50/70 active:scale-95'
          } ${disabled ? 'opacity-40 cursor-not-allowed' : ''}`}
          title="Ouvrir la grille des numéros disponibles"
          aria-label="Sélectionner le numéro"
        >
          <LayoutGrid className="w-4 h-4 stroke-[1.8]" />
        </button>
      </div>

      <p className="text-[10px] text-slate-400 mt-1 flex items-center justify-between">
        <span>{helperText}</span>
        <span className="font-mono text-[9.5px] text-slate-500">
          Libres : <strong className="text-emerald-700">{totalAvailable}</strong> / {maxNumbers}
        </span>
      </p>

      {/* Popover Card Attached under the field (Clean Light Excel UI) */}
      {isOpen && (
        <div className="absolute left-0 right-0 top-full mt-2 z-50 bg-white border border-slate-200 rounded-2xl shadow-xl p-3.5 space-y-3 animate-in fade-in zoom-in-95 duration-150 text-slate-800">
          {/* Popover Header */}
          <div className="flex items-center justify-between pb-2.5 border-b border-slate-100">
            <div className="flex items-center gap-2">
              <div className="w-6 h-6 rounded-lg bg-indigo-50 border border-indigo-200 flex items-center justify-center text-indigo-700">
                <LayoutGrid className="w-3.5 h-3.5" />
              </div>
              <div>
                <h4 className="text-xs font-bold text-slate-900 leading-tight">
                  Grille des Numéros ({prefix}
                  {String(1).padStart(padLength, '0')} à {prefix}
                  {String(maxNumbers).padStart(padLength, '0')})
                </h4>
                <p className="text-[10px] text-slate-400">
                  Les numéros déjà attribués sont grisés et inactifs
                </p>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <div className="text-[10px] font-mono px-2 py-0.5 rounded-md bg-slate-50 border border-slate-200 text-slate-600">
                <span className="text-emerald-700 font-bold">{totalAvailable} libres</span> /{' '}
                <span className="text-rose-700 font-bold">{totalTaken} pris</span>
              </div>
              <button
                type="button"
                onClick={() => setIsOpen(false)}
                className="w-6 h-6 rounded-md text-slate-400 hover:text-slate-700 hover:bg-slate-100 flex items-center justify-center cursor-pointer transition"
                aria-label="Fermer"
              >
                <X className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>

          {/* Bands Navigation Tabs */}
          {bands.length > 1 && (
            <div className="flex items-center gap-1 p-1 bg-slate-100 rounded-xl border border-slate-200/80 overflow-x-auto">
              {bands.map((band) => {
                let bandTaken = 0;
                for (let i = band.start; i <= Math.min(band.end, maxNumbers); i++) {
                  if (takenNumbers.has(i)) bandTaken++;
                }
                const bandTotal = Math.min(band.end, maxNumbers) - band.start + 1;
                const bandAvailable = bandTotal - bandTaken;
                const isActive = activeBandId === band.id;

                return (
                  <button
                    key={band.id}
                    type="button"
                    onClick={() => setActiveBandId(band.id)}
                    className={`flex-1 min-w-[58px] py-1 px-1.5 rounded-lg text-[10.5px] font-bold transition flex flex-col items-center justify-center cursor-pointer ${
                      isActive
                        ? 'bg-white text-indigo-900 shadow-2xs border border-slate-200/70 font-black'
                        : 'text-slate-600 hover:text-slate-900 hover:bg-white/60'
                    }`}
                  >
                    <span>{band.label}</span>
                    <span
                      className={`text-[9px] font-mono ${
                        bandAvailable === 0 ? 'text-rose-600' : 'text-slate-400'
                      }`}
                    >
                      {bandAvailable}/{bandTotal}
                    </span>
                  </button>
                );
              })}

              {/* View All Button */}
              <button
                type="button"
                onClick={() => setActiveBandId('all')}
                className={`py-1 px-2 rounded-lg text-[10px] font-bold transition cursor-pointer shrink-0 ${
                  activeBandId === 'all'
                    ? 'bg-white text-indigo-900 shadow-2xs border border-slate-200/70 font-black'
                    : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                Tous
              </button>
            </div>
          )}

          {/* Grid of Numbers (5 Columns) */}
          <div
            className={`grid gap-1.5 ${
              activeBandId === 'all'
                ? 'grid-cols-5 sm:grid-cols-10 max-h-48 overflow-y-auto pr-1'
                : 'grid-cols-5'
            }`}
          >
            {displayedNumbers.map((num) => {
              const isTaken = takenNumbers.has(num);
              const isSelected = selectedNumber === num;
              const padded = String(num).padStart(padLength, '0');

              if (isTaken) {
                return (
                  <div
                    key={num}
                    title={`Numéro ${prefix}${padded} déjà attribué`}
                    className="h-8 rounded-lg bg-slate-50 border border-slate-100 text-slate-300 font-mono text-xs font-medium flex items-center justify-center cursor-not-allowed select-none line-through"
                  >
                    {padded}
                  </div>
                );
              }

              if (isSelected) {
                return (
                  <button
                    key={num}
                    type="button"
                    onClick={() => handleSelectNumber(num)}
                    title={`Numéro sélectionné : ${prefix}${padded}`}
                    className="h-8 rounded-lg bg-indigo-600 border border-indigo-600 text-white font-mono text-xs font-bold flex items-center justify-center shadow-xs cursor-pointer"
                  >
                    <span>{padded}</span>
                    <Check className="w-2.5 h-2.5 stroke-[3] ml-0.5" />
                  </button>
                );
              }

              return (
                <button
                  key={num}
                  type="button"
                  onClick={() => handleSelectNumber(num)}
                  title={`Attribuer le numéro ${prefix}${padded}`}
                  className="h-8 rounded-lg bg-white hover:bg-indigo-50 hover:border-indigo-300 hover:text-indigo-700 border border-slate-200 text-slate-700 font-mono text-xs font-medium flex items-center justify-center transition active:scale-95 cursor-pointer shadow-2xs"
                >
                  {padded}
                </button>
              );
            })}
          </div>

          {/* Popover Footer */}
          <div className="pt-2.5 border-t border-slate-100 flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-[10.5px]">
            {/* Legend */}
            <div className="flex items-center gap-3 text-slate-500">
              <span className="flex items-center gap-1">
                <span className="w-2.5 h-2.5 rounded-sm bg-white border border-slate-300 inline-block shadow-2xs" />
                <span>Libre</span>
              </span>
              <span className="flex items-center gap-1">
                <span className="w-2.5 h-2.5 rounded-sm bg-slate-100 border border-slate-200 inline-block line-through text-slate-400" />
                <span className="text-slate-400">Attribué (indisponible)</span>
              </span>
              <span className="flex items-center gap-1">
                <span className="w-2.5 h-2.5 rounded-sm bg-indigo-600 inline-block shadow-2xs" />
                <span className="text-indigo-700 font-bold">Sélectionné</span>
              </span>
            </div>

            {/* Quick Actions */}
            <div className="flex items-center gap-2 self-end sm:self-auto">
              {autoGeneratedCode && (
                <button
                  type="button"
                  onClick={() => {
                    handleResetToAuto();
                    setIsOpen(false);
                  }}
                  className="text-indigo-600 hover:text-indigo-800 font-bold flex items-center gap-1 cursor-pointer"
                >
                  <Sparkles className="w-3 h-3 text-indigo-500" />
                  <span>Ordre Auto ({autoGeneratedCode})</span>
                </button>
              )}
              <button
                type="button"
                onClick={() => setIsOpen(false)}
                className="px-2.5 py-1 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-700 font-bold cursor-pointer transition"
              >
                Fermer
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
