import { useState, useEffect, useMemo } from 'react';
import { Package, Plus, X, Sparkles } from 'lucide-react';
import CustomSelect from '../../components/common/CustomSelect';

export default function AddArticleModal({
  isOpen,
  onClose,
  types = [],
  stockItems = [],
  onAddArticle,
  onOpenAddTypeModal,
}) {
  const [selectedType, setSelectedType] = useState('');
  const [ref, setRef] = useState('');
  const [designation, setDesignation] = useState('');
  const [stockInitial, setStockInitial] = useState(0);
  const [seuil, setSeuil] = useState(5);
  const [emplacement, setEmplacement] = useState('R1-B01');

  // Compute next auto ref for the selected type
  const autoGeneratedRef = useMemo(() => {
    if (!selectedType) return '';
    const cleanType = selectedType.trim();
    // Find all items matching this type
    const matching = (stockItems || []).filter(
      (s) =>
        String(s.type || s.id_type || '').toLowerCase() === cleanType.toLowerCase()
    );
    let maxIndex = 0;
    const regex = new RegExp(`^${cleanType}(\\d+)$`, 'i');
    matching.forEach((item) => {
      const match = String(item.ref || '').match(regex);
      if (match) {
        const num = parseInt(match[1], 10);
        if (!isNaN(num) && num > maxIndex) maxIndex = num;
      }
    });
    // If no numbered match found yet, count existing items + 1
    const nextNum = maxIndex > 0 ? maxIndex + 1 : matching.length + 1;
    return `${cleanType}${nextNum}`;
  }, [selectedType, stockItems]);

  useEffect(() => {
    if (isOpen) {
      const initialType = types[0]?.id_type || types[0]?.libelle || 'Courroie';
      setSelectedType(initialType);
      setDesignation('');
      setStockInitial(0);
      setSeuil(5);
      setEmplacement('R1-B01');
    }
  }, [isOpen, types]);

  useEffect(() => {
    if (autoGeneratedRef) {
      setRef(autoGeneratedRef);
    }
  }, [autoGeneratedRef]);

  if (!isOpen) return null;

  const handleSubmit = (e) => {
    e.preventDefault();
    const cleanRef = (ref || autoGeneratedRef).trim();
    if (!cleanRef) return;

    onAddArticle({
      ref: cleanRef,
      designation: designation.trim() || cleanRef,
      id_type: selectedType,
      type: selectedType,
      stockInitial: Number(stockInitial) || 0,
      seuil: Number(seuil) || 0,
      emplacement: emplacement.trim() || 'ATELIER',
    });

    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/45 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto animate-fadeIn">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg border border-slate-200 overflow-hidden flex flex-col">
        {/* Modal Header */}
        <div className="p-4 sm:p-5 border-b border-slate-200 flex items-center justify-between bg-white">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-blue-50 border border-blue-200 flex items-center justify-center text-blue-600 shadow-2xs font-bold">
              <Package className="w-4 h-4" />
            </div>
            <div>
              <h3 className="font-bold text-sm text-slate-900">Nouvel Article (Stock PDR)</h3>
              <p className="text-xs text-slate-500">Ajout d'une pièce avec référence automatique par Type</p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="w-8 h-8 rounded-lg text-slate-400 hover:text-slate-700 hover:bg-slate-100 flex items-center justify-center transition cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="p-4 sm:p-5 space-y-4 text-xs">
          <div>
            {/* Type with '+' Button */}
            <div className="flex items-center justify-between mb-1">
              <label className="text-[11px] font-bold text-slate-700">
                Type de Pièce (Famille)
              </label>
              <button
                type="button"
                onClick={onOpenAddTypeModal}
                className="text-[11px] text-indigo-600 hover:text-indigo-800 font-bold inline-flex items-center gap-0.5 cursor-pointer"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>Nouveau Type</span>
              </button>
            </div>
            <CustomSelect
              value={selectedType}
              onChange={(val) => setSelectedType(val)}
              options={types.map((t) => ({
                value: t.id_type || t.libelle,
                label: `${t.libelle || t.id_type} (${t.id_type || t.libelle})`,
              }))}
              placeholder="-- Sélectionner un Type --"
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="text-[11px] font-bold text-slate-700">
                  Référence (Ref)
                </label>
                <span className="text-[10px] text-indigo-600 font-semibold flex items-center gap-0.5">
                  <Sparkles className="w-2.5 h-2.5" /> Auto-Type
                </span>
              </div>
              <input
                type="text"
                placeholder="ex: Courroie1"
                value={ref}
                onChange={(e) => setRef(e.target.value)}
                className="w-full h-9 px-3 rounded-xl border border-slate-200 bg-slate-50/70 text-xs font-mono font-bold uppercase focus:bg-white focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/15 shadow-2xs transition"
                required
              />
            </div>

            <div>
              <label className="text-[11px] font-bold text-slate-700 block mb-1">
                Désignation (Spécification technique)
              </label>
              <input
                type="text"
                placeholder="ex: 6PK925, Ø12x150, etc."
                value={designation}
                onChange={(e) => setDesignation(e.target.value)}
                className="w-full h-9 px-3 rounded-xl border border-slate-200 bg-white text-xs font-medium focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/15 shadow-2xs transition"
                required
              />
            </div>
          </div>

          <div className="grid grid-cols-3 gap-3">
            <div>
              <label className="text-[11px] font-bold text-slate-700 block mb-1">
                Stock Initial
              </label>
              <input
                type="number"
                min="0"
                value={stockInitial}
                onChange={(e) => setStockInitial(parseInt(e.target.value) || 0)}
                className="w-full h-9 px-3 rounded-xl border border-slate-200 bg-white text-xs font-mono font-bold focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/15 shadow-2xs transition"
                required
              />
            </div>

            <div>
              <label className="text-[11px] font-bold text-slate-700 block mb-1">
                Seuil d'Alerte
              </label>
              <input
                type="number"
                min="0"
                value={seuil}
                onChange={(e) => setSeuil(parseInt(e.target.value) || 0)}
                className="w-full h-9 px-3 rounded-xl border border-slate-200 bg-white text-xs font-mono font-bold text-amber-700 focus:border-amber-500 focus:ring-2 focus:ring-amber-500/15 shadow-2xs transition"
                required
              />
            </div>

            <div>
              <label className="text-[11px] font-bold text-slate-700 block mb-1">
                Emplacement
              </label>
              <input
                type="text"
                placeholder="R1-B01"
                value={emplacement}
                onChange={(e) => setEmplacement(e.target.value)}
                className="w-full h-9 px-3 rounded-xl border border-slate-200 bg-white text-xs font-mono font-medium focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/15 shadow-2xs transition"
              />
            </div>
          </div>

          {/* Modal Actions */}
          <div className="pt-3 border-t border-slate-200 flex items-center justify-end gap-2.5">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl border border-slate-200 bg-white hover:bg-slate-100 text-slate-700 font-semibold transition cursor-pointer text-xs shadow-2xs"
            >
              Annuler
            </button>
            <button
              type="submit"
              className="px-5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold transition shadow-xs cursor-pointer text-xs flex items-center gap-1.5 active:scale-[0.98]"
            >
              <Plus className="w-3.5 h-3.5" />
              <span>Enregistrer l'Article</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
