import { useState, useEffect, useMemo } from 'react';
import { MapPin, Plus, X } from 'lucide-react';
import SequentialCodePicker from '../../components/common/SequentialCodePicker';

export default function AddZoneModal({ isOpen, onClose, zones = [], onAddZone }) {
  const [form, setForm] = useState({
    code_zone: '',
    id_zone: '',
    libelle: '',
    type: 'FINITION',
    description: '',
  });
  const [error, setError] = useState('');

  const autoZoneCode = useMemo(() => {
    const nums = zones
      .map((z) => {
        const val = z.code_zone || z.code || z.id_zone || '';
        const m = String(val).match(/ZONE-(\d+)/i);
        return m ? parseInt(m[1], 10) : 0;
      })
      .filter((n) => !isNaN(n));
    const max = nums.length > 0 ? Math.max(...nums) : 0;
    return `ZONE-${String(max + 1).padStart(2, '0')}`;
  }, [zones]);

  const takenZoneNumbers = useMemo(() => {
    const set = new Set();
    zones.forEach((z) => {
      const val = z.code_zone || z.code || z.id_zone || '';
      const m = String(val).match(/(\d+)$/);
      if (m) set.add(parseInt(m[1], 10));
    });
    return set;
  }, [zones]);

  useEffect(() => {
    if (isOpen) {
      setForm({
        code_zone: autoZoneCode,
        id_zone: '',
        libelle: '',
        type: 'FINITION',
        description: '',
      });
      setError('');
    }
  }, [isOpen, autoZoneCode]);

  if (!isOpen) return null;

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!form.code_zone.trim()) {
      setError('Veuillez sélectionner ou générer un Code Zone.');
      return;
    }
    if (!form.id_zone.trim()) {
      setError("Veuillez saisir l'ID Zone (ex: POL, DET, AMBO).");
      return;
    }
    if (!form.libelle.trim()) {
      setError('Veuillez saisir le libellé de la zone.');
      return;
    }

    if (zones.some((z) => z.id_zone && z.id_zone.toLowerCase().trim() === form.id_zone.toLowerCase().trim())) {
      setError("Cet ID de zone existe déjà.");
      return;
    }

    onAddZone({
      code_zone: form.code_zone.trim().toUpperCase(),
      id_zone: form.id_zone.trim().toUpperCase(),
      libelle: form.libelle.trim(),
      type: form.type.trim().toUpperCase(),
      description: form.description.trim(),
    });

    onClose();
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/45 backdrop-blur-xs overflow-y-auto animate-fadeIn">
      <div className="bg-white rounded-2xl max-w-md w-full border border-slate-200 shadow-2xl flex flex-col">
        {/* Header */}
        <div className="p-4 sm:p-5 bg-white border-b border-slate-200 flex items-center justify-between rounded-t-2xl">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-purple-50 border border-purple-200 flex items-center justify-center text-purple-700 shadow-2xs font-bold">
              <MapPin className="w-4 h-4" />
            </div>
            <div>
              <h3 className="font-bold text-sm text-slate-900 leading-tight">Nouvelle Zone / Atelier</h3>
              <p className="text-[11.5px] text-slate-500 mt-0.5">
                Création et intégration directe au workflow
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="w-8 h-8 rounded-lg text-slate-400 hover:text-slate-700 hover:bg-slate-100 flex items-center justify-center transition cursor-pointer"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Form Body */}
        <div className="p-4 sm:p-5 overflow-y-auto max-h-[calc(100vh-120px)]">
          <form onSubmit={handleSubmit} className="space-y-4 text-xs">
            {error && (
              <div className="p-2.5 rounded-xl bg-rose-50 border border-rose-200 text-rose-700 text-xs font-medium">
                {error}
              </div>
            )}

            {/* Code Zone (Automatic / Sequential Picker) */}
            <div>
              <SequentialCodePicker
                prefix="ZONE-"
                currentCode={form.code_zone}
                onChangeCode={(newCode) => setForm((prev) => ({ ...prev, code_zone: newCode }))}
                autoGeneratedCode={autoZoneCode}
                takenNumbers={takenZoneNumbers}
                label="Code Zone (ex: ZONE-01) *"
                helperText="Code séquentiel système avec choix libre du numéro"
              />
            </div>

            {/* ID Zone (Manual User Identifier) */}
            <div>
              <label className="text-[11px] font-bold text-slate-700 block mb-1">
                ID Zone (ex: POL, DET, AMBO) <span className="text-rose-500">*</span>
              </label>
              <input
                type="text"
                required
                placeholder="ex: POL, DET, AMBO..."
                value={form.id_zone}
                onChange={(e) => setForm({ ...form, id_zone: e.target.value.toUpperCase() })}
                className="w-full h-9 px-3 rounded-xl bg-white border border-slate-200 text-xs font-mono font-bold text-slate-900 placeholder:text-slate-400 focus:outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-500/15 shadow-2xs transition"
              />
              <p className="text-[10.5px] text-slate-400 mt-1">Identifiant manuel utilisateur (ex: DET, POL, SAT, AMBO)</p>
            </div>

            {/* Libellé */}
            <div>
              <label className="text-[11px] font-bold text-slate-700 block mb-1">
                Libellé / Désignation de l'Atelier <span className="text-rose-500">*</span>
              </label>
              <input
                type="text"
                required
                placeholder="ex: Polissage, Emboutissage..."
                value={form.libelle}
                onChange={(e) => setForm({ ...form, libelle: e.target.value })}
                className="w-full h-9 px-3 rounded-xl bg-white border border-slate-200 text-xs text-slate-900 placeholder:text-slate-400 focus:outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-500/15 shadow-2xs transition"
              />
            </div>

            {/* Type */}
            <div>
              <label className="text-[11px] font-bold text-slate-700 block mb-1">
                Type de Zone
              </label>
              <select
                value={form.type}
                onChange={(e) => setForm({ ...form, type: e.target.value })}
                className="w-full h-9 px-3 rounded-xl bg-white border border-slate-200 text-xs text-slate-900 focus:outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-500/15 shadow-2xs transition"
              >
                <option value="FINITION">FINITION</option>
                <option value="DECOUPE">DECOUPE</option>
                <option value="SUPPORT">SUPPORT</option>
                <option value="FORMAGE">FORMAGE</option>
                <option value="ASSEMBLAGE_FINAL">ASSEMBLAGE FINAL</option>
                <option value="STOCK">STOCK</option>
                <option value="AUTRE">AUTRE</option>
              </select>
            </div>

            {/* Description */}
            <div>
              <label className="text-[11px] font-bold text-slate-700 block mb-1">
                Description (Philosophie Industrielle)
              </label>
              <textarea
                rows={3}
                placeholder="Principe physique et mécanique de l'opération..."
                value={form.description}
                onChange={(e) => setForm({ ...form, description: e.target.value })}
                className="w-full p-3 rounded-xl bg-white border border-slate-200 text-xs text-slate-900 placeholder:text-slate-400 focus:outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-500/15 shadow-2xs transition resize-none"
              />
            </div>

            {/* Actions */}
            <div className="flex items-center justify-end gap-2.5 pt-3 border-t border-slate-200">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 rounded-xl border border-slate-200 bg-white hover:bg-slate-100 text-slate-700 font-semibold transition cursor-pointer text-xs shadow-2xs"
              >
                Annuler
              </button>
              <button
                type="submit"
                className="px-5 py-2 rounded-xl bg-purple-600 hover:bg-purple-700 text-white font-bold transition shadow-xs cursor-pointer text-xs flex items-center gap-1.5 active:scale-[0.98]"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>Créer la Zone</span>
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
